routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\MahasiswaController;
use App\Http\Controllers\ArticleController;
use Illuminate\Http\Request;

Route::resource('mahasiswas', MahasiswaController::class);
Route::post('cari', [MahasiswaController::class, 'cari'])->name('cari');
Route::get('mahasiswa/nilai/{nim}', [MahasiswaController::class, 'nilai'])->name('nilai');
Route::get('/article/cetak_pdf', [ArticleController::class, 'cetak_pdf']);
Route::get('/mahasiswas/{nim}/exportPDF', [MahasiswaController::class, 'exportPDF'])->name('mahasiswas.exportPDF');


Route::resource('articles', ArticleController::class);

Route::get('/', function () {
    return view('welcome');
});

app/Models/Mahasiswa.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\Mahasiswa as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Database\Eloquent\Model; //Model Eloquent
use App\Models\Mahasiswa;

class Mahasiswa extends Model //Definisi Model
{
    protected $table="mahasiswas"; // Eloquent akan membuat model mahasiswa menyimpan record di tabel mahasiswas
    protected $primaryKey = 'nim'; // Memanggil isi DB Dengan primarykey
 /**
 * The attributes that are mass assignable.
 *
 * @var array
 */
    protected $fillable = [
        'nim',
        'nama',
        'foto',
        'kelas_id',
        'jurusan',
        'no_handphone',
        'email',
        'tgl_lahir',
    ];

    public function kelas()
    {
        return $this->belongsTo(Kelas::class);
    }

    public function matakuliah()
    {
        return $this->belongsToMany(MataKuliah::class);
    }
};

app/Http/Controllers/MahasiswaController.php
<?php

namespace App\Http\Controllers;

use App\Models\Mahasiswa;
use App\Models\Kelas;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Pagination\Paginator;
use Illuminate\Support\Facades\DB;
use PDF;


class MahasiswaController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        //fungsi eloquent menampilkan data menggunakan pagination
        // $mahasiswas = Mahasiswa::all(); // Mengambil semua isi tabel
        // $posts = Mahasiswa::orderBy('nim', 'desc')->paginate(6);
        // return view('mahasiswas.index', compact('mahasiswas'));
        // with('i', (request()->input('page', 1) - 1) * 5);
        // $mahasiswas = Mahasiswa::paginate(5);
        // return view('mahasiswas.index', compact('mahasiswas'));

        //yang semula Mahasiswa::all, diubah menjadi with() yang menyatakan relasi
        $mahasiswas = Mahasiswa::with('kelas');
        $paginate = Mahasiswa::orderBy('nim', 'asc')->paginate(5);
        return view('mahasiswas.index', ['mahasiswas' => $mahasiswas, 'paginate' => $paginate]);
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        $kelas = Kelas::all(); //mendapatkan data dari tabel kelas
        return view('mahasiswas.create', ['kelas' => $kelas]);
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        // dd($request->file('foto'));
        //melakukan validasi data
        $request->validate([
            'nim' => 'required',
            'nama' => 'required',
            'foto' => 'required|image|max:2048',
            'kelas' => 'required',
            'jurusan' => 'required',
            'no_handphone' => 'required',
            'email' => 'required',
            'tgl_lahir' => 'required',
            ]);

            $imageName = time().'.'.$request->foto->extension();  
            $request->foto->move(public_path('storage'), $imageName);
            // $fileFoto = $request->file('foto');
            // $namaFoto = time() . '-' . $fileFoto->getClientOriginalName();
            // dd($namaFoto);
            // $fileFoto->storeAs('public/images', $namaFoto);

            $mahasiswa = new Mahasiswa;
            $mahasiswa->nim = $request->get('nim');
            $mahasiswa->nama = $request->get('nama');
            $mahasiswa->foto = $imageName;
            $mahasiswa->jurusan = $request->get('jurusan');
            $mahasiswa->no_handphone = $request->get('no_handphone');
            $mahasiswa->email = $request->get('email');
            $mahasiswa->tgl_lahir = $request->get('tgl_lahir');
            $mahasiswa->save();

            $kelas = new Kelas;
            $kelas->id = $request->get('kelas');

            //fungsi eloquent untuk menambah data dengan relasi belongsTo
            $mahasiswa->kelas()->associate($kelas);
            $mahasiswa->save();

            //jika data berhasil ditambahkan, akan kembali ke halaman utama
            return redirect()->route('mahasiswas.index')->with('success', 'Mahasiswa Berhasil Ditambahkan');
   
    }

    /**
     * Display the specified resource.
     */
    public function show($nim)
    {
    //menampilkan detail data dengan menemukan/berdasarkan Nim Mahasiswa

    $mahasiswas = Mahasiswa::with('kelas')->where('nim', $nim)->first();
    return view('mahasiswas.detail', ['mahasiswas' => $mahasiswas]);
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit($nim)
    {
       //menampilkan detail data dengan menemukan berdasarkan Nim Mahasiswa untuk diedit
        $mahasiswa = Mahasiswa::with('kelas')->where('nim', $nim)->first();
        $kelas = Kelas::all();
        return view('mahasiswas.edit', compact('mahasiswa', 'kelas'));
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, string $nim)
    {
        // dd($request->file('foto'));

        
        //melakukan validasi data
        $request->validate([
            'nim' => 'required',
            'nama' => 'required',
            'foto' => 'required',
            'kelas' => 'required',
            'jurusan' => 'required',
            'no_handphone' => 'required',
            'email' => 'required',
            'tgl_lahir' => 'required',
            ]);

            $mahasiswa = Mahasiswa::with('kelas')->where('nim', $nim)->first();
            $mahasiswa->nim = $request->get('nim');
            $mahasiswa->nama = $request->get('nama');
            $mahasiswa->jurusan = $request->get('jurusan');
            $mahasiswa->no_handphone = $request->get('no_handphone');
            $mahasiswa->email = $request->get('email');
            $mahasiswa->tgl_lahir = $request->get('tgl_lahir');
            $mahasiswa->save();

            if($request->file('foto')){
                // hapus foto lama jika ada foto baru yang diupload
                if($mahasiswa->foto && file_exists(storage_path('app/public/'.$mahasiswa->foto))){
                    \Storage::delete('public/'.$mahasiswa->foto);
                }
                // simpan foto baru ke direktori penyimpanan
                $file = $request->file('foto');
                $nama_file = $file->getClientOriginalName();
                $file->storeAs('public/foto', $nama_file);
                // simpan nama file foto ke dalam kolom 'foto' pada tabel 'mahasiswas'
                $mahasiswa->foto = $nama_file;
            }              
            $image_name = $request->file('foto')->store('images', 'public');
            $mahasiswa->foto = $image_name;
           
            $kelas = new Kelas;
            $kelas->id = $request->get('kelas');

            $mahasiswa->kelas()->associate($kelas);
            $mahasiswa->save();

            return redirect()->route('mahasiswas.index')->with('success', 'Mahasiswa Berhasil Diupdate');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy($nim)
    {
        //fungsi eloquent untuk menghapus data
        Mahasiswa::find($nim)->delete();
        return redirect()->route('mahasiswas.index')
            -> with('success', 'Mahasiswa Berhasil Dihapus');

    }
    public function cari(Request $request)
    {
        $cariMhs = $request->cariMhs;
        $paginate = Mahasiswa::where('nama', 'like', '%'.$cariMhs.'%')->paginate(5);
        return view('mahasiswas.index', compact('paginate'));
    }

    public function nilai($nim)
    {
        $mahasiswas = Mahasiswa::with('matakuliah')->where('nim', $nim)->first();
        $nilai = DB::table('mahasiswa_mata_kuliah')
                    ->join('matakuliah', 'matakuliah.id', '=', 'mahasiswa_mata_kuliah.mata_kuliah_id')
                    ->where('mahasiswa_mata_kuliah.mahasiswa_nim', $nim)
                    ->select('nilai')
                    ->get();

        return view('mahasiswas.nilai', ['mahasiswas' => $mahasiswas, 'nilai' => $nilai]);
    }

    public function exportPDF($nim)
    {
        $mahasiswas = Mahasiswa::with('matakuliah')->where('nim', $nim)->first();
        $nilai = DB::table('mahasiswa_mata_kuliah')
                    ->join('matakuliah', 'matakuliah.id', '=', 'mahasiswa_mata_kuliah.mata_kuliah_id')
                    ->where('mahasiswa_mata_kuliah.mahasiswa_nim', $nim)
                    ->select('nilai')
                    ->get();
        $pdf = PDF::loadView('mahasiswas.nilai_pdf', ['mahasiswas' => $mahasiswas, 'nilai' => $nilai]);
        return $pdf->download('KHS-' . $mahasiswas->nama . '.pdf');
        
    }

}

resources/views/mahasiswas/create.blade.php
@extends('mahasiswas.layout')
@section('content')
<div class="container mt-5">
   <div class="row justify-content-center align-items-center">
   <div class="card" style="width: 24rem;">
   <div class="card-header">Tambah Mahasiswa</div>
   
   <div class="card-body">
      @if ($errors->any())
      <div class="alert alert-danger">      
         <strong>Whoops!</strong> There were some problems with your input.<br><br>
         <ul>
            @foreach ($errors->all() as $error)
            <li>{{ $error }}</li>
            @endforeach
         </ul>
      </div>
      @endif
      
      <form method="post" action="{{ route('mahasiswas.store') }}" id="myForm" enctype="multipart/form-data">
         @csrf
         <div class="form-group">
            <label for="nim">Nim</label> 
            <input type="text" name="nim" class="form-control" id="nim" aria-describedby="nim" > 
         </div>
         <div class="form-group">
            <label for="nama">Nama</label> 
            <input type="text" name="nama" class="form-control" id="nama" aria-describedby="nama" > 
         </div>
         <div class="form-group">
            <label for="foto">Foto Mahasiswa: </label>
            <input type="file" class="form-control" required="required" name="foto"></br>
         </div>
         <div class="form-group">
            <label for="kelas">Kelas</label>
            <select name="kelas" class="form-control">
               @foreach($kelas as $kls)
                  <option value="{{$kls->id}}">{{$kls->nama_kelas}}</option>
               @endforeach
            </select>
         </div>
         <div class="form-group">
            <label for="jurusan">Jurusan</label> 
            <input type="text" name="jurusan" class="form-control" id="jurusan" aria-describedby="jurusan" > 
         </div>
         <div class="form-group">
            <label for="no_handphone">No Handphone</label> 
            <input type="text" name="no_handphone" class="form-control" id="no_handphone" aria-describedby="no_handphone" > 
         </div>
         <div class="form-group">
            <label for="email">Email</label> 
            <input type="text" name="email" class="form-control" id="email" aria-describedby="email" > 
         </div>
         <div class="form-group">
            <label for="tgl_lahir">Tanggal Lahir</label> 
            <input type="date" name="tgl_lahir" class="form-control" id="tgl_lahir" aria-describedby="tgl_lahir" > 
         </div>
         <button type="submit" class="btn btn-primary">Submit</button>
      </form>
   </div>
</div>
</div>
</div>
@endsection

resources/views/mahasiswas/detail.blade.php
@extends('mahasiswas.layout')
 @section('content')
 <div class="container mt-5">
    <div class="row justify-content-center align-items-center">
        <div class="card" style="width: 24rem;">
        <div class="card-header">Detail Mahasiswa</div>
        <div class="card-body">
            <ul class="list-group list-group-flush">
                <li class="list-group-item"><b>Nim: </b>{{$mahasiswas->nim}}</li>
                <li class="list-group-item"><b>Nama: </b>{{$mahasiswas->nama}}</li>
                <li class="list-group-item"><b>Kelas: </b>{{$mahasiswas->kelas->nama_kelas}}</li>
                <li class="list-group-item"><b>Jurusan: </b>{{$mahasiswas->jurusan}}</li>
                <li class="list-group-item"><b>No Handphone: </b>{{$mahasiswas->no_handphone}}</li>
                <li class="list-group-item"><b>Email: </b>{{$mahasiswas->email}}</li>
                <li class="list-group-item"><b>Tanggal Lahir: </b>{{$mahasiswas->tgl_lahir}}</li>
            </ul>
        </div>
        <a class="btn btn-success mt-3" href="{{ route('mahasiswas.index') }}">Kembali</a>
    </div>
</div>
</div>
@endsection

resources/views/mahasiswas/edit.blade.php
@extends('mahasiswas.layout')
 @section('content')
 <div class="container mt-5">
    <div class="row justify-content-center align-items-center">
        <div class="card" style="width: 24rem;">
        <div class="card-header">Edit Mahasiswa</div>
        <div class="card-body">
            @if ($errors->any())
            <div class="alert alert-danger">
                <strong>Whoops!</strong> There were some problems with your input.<br><br>
                <ul>
                    @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
            @endif
            <form method="post" action="{{ route('mahasiswas.update', $mahasiswa->nim) }}" id="myForm" enctype="multipart/form-data">
                @csrf
                @method('PUT')
                <div class="form-group">
                    <label for="nim">Nim</label> 
                    <input type="text" name="nim" class="form-control" id="nim" value="{{ $mahasiswa->nim }}" aria-describedby="nim" > 
                </div>
                <div class="form-group">
                    <label for="nama">Nama</label> 
                    <input type="text" name="nama" class="form-control" id="nama" value="{{ $mahasiswa->nama }}" aria-describedby="nama" > 
                </div>
                <div class="form-group">
                    <label for="foto">Foto Mahasiswa</label>
                    <input type="file" class="form-control" required="required" name="foto"></br>
                    <img width="100px" height="100px" src="{{asset('storage/'.$mahasiswa->foto)}}">
                </div>
                <div class="form-group">
                    <label for="kelas">Kelas</label>
                    <select name="kelas" class="form-control">
                        @foreach($kelas as $kls)
                            <option value="{{$kls->id}}" {{ $mahasiswa->kelas_id == $kls->id ? 'selected' : '' }}>{{$kls->nama_kelas}}</option>
                        @endforeach
                    </select>
                </div>
                <div class="form-group">
                    <label for="jurusan">Jurusan</label> 
                    <input type="text" name="jurusan" class="form-control" id="jurusan" value="{{ $mahasiswa->jurusan }}" aria-describedby="jurusan" > 
                </div>
                <div class="form-group">
                    <label for="no_handphone">No Handphone</label> 
                    <input type="text" name="no_handphone" class="form-control" id="no_handphone" value="{{ $mahasiswa->no_handphone }}" aria-describedby="no_handphone" > 
                </div>
                <div class="form-group">
                    <label for="email">Email</label> 
                    <input type="text" name="email" class="form-control" id="email" value="{{ $mahasiswa->email }}" aria-describedby="email" > 
                </div>
                <div class="form-group">
                    <label for="tgl_lahir">Tanggal Lahir</label> 
                    <input type="date" name="tgl_lahir" class="form-control" id="tgl_lahir" value="{{ $mahasiswa->tgl_lahir }}" aria-describedby="tgl_lahir" > 
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
    </div>
</div>
</div>
@endsection

resources/views/mahasiswas/index.blade.php
@extends('mahasiswas.layout')
@section('content')
<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left mt-2">
            <h2>JURUSAN TEKNOLOGI INFORMASI-POLITEKNIK NEGERI MALANG</h2>
        </div>
    </div>
</div>
<form class="row mb-3 mt-5" action="{{ route('cari') }}" method="POST">
    @csrf
    <div class="col-md-5">
        <div class="d-flex flex-row">
            <input type="text" value="{{ (request()->cariMhs) ? request()->cariMhs : '' }}" name="cariMhs" class="form-control" placeholder="Cari Mahasiswa">
            <button type="submit" class="btn btn-primary ml-3">Cari</button>
        </div>
    </div>
    <div class="col-md-6 d-flex flex-row justify-content-end">
        <a class="btn btn-success" href="{{ route('mahasiswas.create') }}"> Input Mahasiswa</a>
    </div>
</form>

@if ($message = Session::get('success'))
<div class="alert alert-success">
    <p>{{ $message }}</p>
</div>
@endif

<table class="table table-bordered">
    <tr>
        <th>Nim</th>
        <th>Nama</th>
        <th>Foto</th>
        <th>Kelas</th>
        <th>Jurusan</th>
        <th>No Handphone</th>
        <th>Email</th>
        <th>Tanggal Lahir</th>
        <th width="280px">Action</th>
    </tr>
    
    @foreach ($paginate as $mhs)
    <tr>
        <td>{{ $mhs->nim }}</td>
        <td>{{ $mhs->nama }}</td>
        <td><img src="{{ asset('storage/'.$mhs->foto) }}" alt="Foto Mahasiswa" width="100"></td>
        <td>{{ $mhs->kelas->nama_kelas }}</td>
        <td>{{ $mhs->jurusan }}</td>
        <td>{{ $mhs->no_handphone }}</td>
        <td>{{ $mhs->email }}</td>
        <td>{{ $mhs->tgl_lahir }}</td>
        <td>
            <form action="{{ route('mahasiswas.destroy',$mhs->nim) }}" method="POST">
                <a class="btn btn-info" href="{{ route('mahasiswas.show',$mhs->nim) }}">Show</a>
                <a class="btn btn-primary" href="{{ route('mahasiswas.edit',$mhs->nim) }}">Edit</a>
                @csrf
                @method('DELETE')
                <button type="submit" class="btn btn-danger">Delete</button>
                <a class="btn btn-warning" href="{{ route('nilai',$mhs->nim) }}">Nilai</a>
            </form>
        </td>
    </tr>
    @endforeach
</table>
<div class="col-md-12">
    {{ $paginate->links() }}
</div>
@endsection

resources/views/mahasiswas/layout.blade.php
<html>
    <head>
        <title>Sistem Informasi Mahasiswa</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    </head>
    <body>
        <div class="container">
            @yield('content')
        </div>
    </body>
</html>

resources/views/mahasiswas/nilai.blade.php
@extends('mahasiswas.layout')
@section('content')
<div class="row">
<div class="col-lg-12 margin-tb" style="justify-content: center; align-items: center; text-align: center;">
    <div class="pull-left mt-2">
        <h2>JURUSAN TEKNOLOGI INFORMASI-POLITEKNIK NEGERI MALANG</h2>
        <h1 style="margin-top: 30px">KARTU HASIL STUDI (KHS)</h1>
    </div>
</div>

    <div class="left-text" style="margin-top: 40px">
        <p><b>Nama : </b>{{$mahasiswas->nama}}</p>
        <p><b>NIM : </b>{{$mahasiswas->nim}}</p>
        <p><b>Kelas : </b>{{$mahasiswas->kelas->nama_kelas}}</p>
    </div>
    <table class="table table-bordered">
            <tr>
                <th>Mata Kuliah</th>
                <th>SKS</th>
                <th>Semester</th>
                <th>Nilai</th>
            </tr>
            @foreach ($mahasiswas->matakuliah as $mhs)
                <tr>
                    <td>{{ $mhs->nama_matkul }}</td>
                    <td>{{ $mhs->sks }}</td>
                    <td>{{ $mhs->semester }}</td>
                    @php
                        $n = $nilai->where('mahasiswa_nim', $mhs->nim)->first();
                    @endphp
                    <td>
                        @if($n)
                            {{ $n->nilai }}
                        @else
                            Nilai belum diisi
                        @endif
                    </td>
                </tr>
            @endforeach
        </table>
        <div class="text-center mt-5">
            <a class="btn btn-primary" href="{{ route('mahasiswas.exportPDF', $mahasiswas->nim) }}" target="_blank">Cetak ke PDF</a>
        </div>
@endsection

resources/views/mahasiswas/nilai_pdf.blade.php
@extends('mahasiswas.layout')
@section('content')
<!DOCTYPE html>
<html>
    <head>
        <title>KHS Mahasiswa</title>
    </head>
    <body>
        <div class="row">
            <div class="col-lg-12 margin-tb" style="justify-content: center; align-items: center; text-align: center;">
            <div class="pull-left mt-2">
                <h2>JURUSAN TEKNOLOGI INFORMASI-POLITEKNIK NEGERI MALANG</h2>
                <h1 style="margin-top: 30px">KARTU HASIL STUDI (KHS)</h1>
            </div>
        </div>
        <div class="left-text" style="margin-top: 40px">
            <p><b>Nama : </b>{{$mahasiswas->nama}}</p>
            <p><b>NIM : </b>{{$mahasiswas->nim}}</p>
            <p><b>Kelas : </b>{{$mahasiswas->kelas->nama_kelas}}</p>
        </div>
        <table class="table table-bordered">
            <tr>
                <th>Mata Kuliah</th>
                <th>SKS</th>
                <th>Semester</th>
                <th>Nilai</th>
            </tr>
            @foreach ($mahasiswas->matakuliah as $mhs)
                <tr>
                    <td>{{ $mhs->nama_matkul }}</td>
                    <td>{{ $mhs->sks }}</td>
                    <td>{{ $mhs->semester }}</td>
                    @php
                        $n = $nilai->where('mahasiswa_nim', $mhs->nim)->first();
                    @endphp
                    <td>
                        @if($nilai)
                            {{ $n->nilai }}
                        @else
                            Nilai belum diisi
                        @endif
                    </td>
                </tr>
            @endforeach
        </table>
    </body>
</html>
@endsection